"""Flex XML → SQLite schema. GENERATED FILE — do not edit by hand.

Regenerate with::

    python scripts/audit_flex_xml.py --src ~/.ibkr_core/flex_archive

Every attribute IBKR emits gets a column. That is the whole point: the previous
trade dataset was built by a parser that kept 10 of 85 attributes and silently
dropped the rest, and nothing detected it for months. Deriving the column set from
the statements themselves makes "every attribute has a column" a testable invariant
(see tests/test_flex_schema.py) instead of a promise.

Keying
------
``Trade`` is keyed by ``execution_key`` so a fill arriving from the live Client
Portal API and the same fill arriving later from Flex converge on one row:

    execution_key = ibExecID            when non-empty
                  = "flex:" + tradeID   otherwise   (exactly one 2021 trade)

Every other element is keyed by ``row_uid``, a deterministic content hash that also
folds in how many times that exact content has already been seen *within the same
statement*. Byte-identical sibling rows do occur (10 of them, in ``Lot`` and
``WashSale``), so a plain content hash would silently drop them, while a plain
positional key would defeat de-duplication across the overlapping statement windows.
"""

from __future__ import annotations

from typing import Any

#: Source archive audited to build this file: 20 statements.
ELEMENTS: dict[str, dict[str, Any]] = {
    "ConversionRate": {
        "table": "flex_conversion_rate",
        "key": "row_uid",
        "columns": {
            "fromCurrency": ("from_currency", "TEXT"),
            "rate": ("rate", "REAL"),
            "reportDate": ("report_date", "TEXT"),
            "toCurrency": ("to_currency", "TEXT"),
        },
    },
    "StatementOfFundsLine": {
        "table": "flex_statement_of_funds_line",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "acctAlias": ("acct_alias", "TEXT"),
            "actionID": ("action_id", "INTEGER"),
            "activityCode": ("activity_code", "TEXT"),
            "activityDescription": ("activity_description", "TEXT"),
            "amount": ("amount", "REAL"),
            "assetCategory": ("asset_category", "TEXT"),
            "balance": ("balance", "REAL"),
            "buySell": ("buy_sell", "TEXT"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "credit": ("credit", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "date": ("date", "TEXT"),
            "debit": ("debit", "REAL"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "multiplier": ("multiplier", "REAL"),
            "orderID": ("order_id", "INTEGER"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDate": ("settle_date", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "tradeCode": ("trade_code", "TEXT"),
            "tradeCommission": ("trade_commission", "REAL"),
            "tradeGross": ("trade_gross", "REAL"),
            "tradeID": ("trade_id", "INTEGER"),
            "tradePrice": ("trade_price", "REAL"),
            "tradeQuantity": ("trade_quantity", "REAL"),
            "tradeTax": ("trade_tax", "REAL"),
            "transactionID": ("transaction_id", "INTEGER"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "weight": ("weight", "REAL"),
        },
    },
    "Trade": {
        "table": "flex_trade",
        "key": "execution_key",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "TEXT"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "INTEGER"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "INTEGER"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "INTEGER"),
            "positionActionID": ("position_action_id", "INTEGER"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "INTEGER"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "INTEGER"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "UnbundledCommissionDetail": {
        "table": "flex_unbundled_commission_detail",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerClearingCharge": ("broker_clearing_charge", "REAL"),
            "brokerExecutionCharge": ("broker_execution_charge", "REAL"),
            "buySell": ("buy_sell", "TEXT"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "multiplier": ("multiplier", "REAL"),
            "orderReference": ("order_reference", "TEXT"),
            "other": ("other", "INTEGER"),
            "price": ("price", "REAL"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "regFINRATradingActivityFee": ("reg_finra_trading_activity_fee", "REAL"),
            "regOther": ("reg_other", "REAL"),
            "regSection31TransactionFee": ("reg_section31_transaction_fee", "REAL"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "thirdPartyClearingCharge": ("third_party_clearing_charge", "INTEGER"),
            "thirdPartyExecutionCharge": ("third_party_execution_charge", "REAL"),
            "thirdPartyRegulatoryCharge": ("third_party_regulatory_charge", "REAL"),
            "totalCommission": ("total_commission", "REAL"),
            "tradeID": ("trade_id", "INTEGER"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "weight": ("weight", "REAL"),
        },
    },
    "Order": {
        "table": "flex_order",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "TEXT"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "INTEGER"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "TEXT"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "positionActionID": ("position_action_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "TEXT"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "TEXT"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "Lot": {
        "table": "flex_lot",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "REAL"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "TEXT"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "TEXT"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "positionActionID": ("position_action_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "TEXT"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "INTEGER"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "CashTransaction": {
        "table": "flex_cash_transaction",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "acctAlias": ("acct_alias", "TEXT"),
            "actionID": ("action_id", "INTEGER"),
            "amount": ("amount", "REAL"),
            "assetCategory": ("asset_category", "TEXT"),
            "availableForTradingDate": ("available_for_trading_date", "TEXT"),
            "clientReference": ("client_reference", "TEXT"),
            "code": ("code", "TEXT"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "dividendType": ("dividend_type", "TEXT"),
            "exDate": ("ex_date", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "multiplier": ("multiplier", "REAL"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDate": ("settle_date", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "tradeID": ("trade_id", "INTEGER"),
            "transactionID": ("transaction_id", "INTEGER"),
            "type": ("type", "TEXT"),
            "underlyingConid": ("underlying_conid", "TEXT"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "weight": ("weight", "REAL"),
        },
    },
    "WashSale": {
        "table": "flex_wash_sale",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "REAL"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "TEXT"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "TEXT"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "positionActionID": ("position_action_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "TEXT"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "TEXT"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "TEXT"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "SymbolSummary": {
        "table": "flex_symbol_summary",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "TEXT"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "TEXT"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "TEXT"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "positionActionID": ("position_action_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "TEXT"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "TEXT"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "SecurityInfo": {
        "table": "flex_security_info",
        "key": "row_uid",
        "columns": {
            "assetCategory": ("asset_category", "TEXT"),
            "code": ("code", "TEXT"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "isin": ("isin", "TEXT"),
            "issueDate": ("issue_date", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "maturity": ("maturity", "TEXT"),
            "multiplier": ("multiplier", "REAL"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settlementPolicyMethod": ("settlement_policy_method", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "underlyingCategory": ("underlying_category", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "weight": ("weight", "REAL"),
        },
    },
    "OpenPosition": {
        "table": "flex_open_position",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "code": ("code", "TEXT"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "INTEGER"),
            "costBasisMoney": ("cost_basis_money", "REAL"),
            "costBasisPrice": ("cost_basis_price", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "fifoPnlUnrealized": ("fifo_pnl_unrealized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "markPrice": ("mark_price", "REAL"),
            "model": ("model", "TEXT"),
            "multiplier": ("multiplier", "REAL"),
            "openDateTime": ("open_date_time", "TEXT"),
            "openPrice": ("open_price", "REAL"),
            "originatingOrderID": ("originating_order_id", "TEXT"),
            "originatingTransactionID": ("originating_transaction_id", "TEXT"),
            "percentOfNAV": ("percent_of_nav", "REAL"),
            "position": ("position", "REAL"),
            "positionValue": ("position_value", "REAL"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "side": ("side", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "underlyingConid": ("underlying_conid", "INTEGER"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "vestingDate": ("vesting_date", "TEXT"),
            "weight": ("weight", "REAL"),
        },
    },
    "AssetSummary": {
        "table": "flex_asset_summary",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "accruedInt": ("accrued_int", "REAL"),
            "acctAlias": ("acct_alias", "TEXT"),
            "assetCategory": ("asset_category", "TEXT"),
            "brokerageOrderID": ("brokerage_order_id", "TEXT"),
            "buySell": ("buy_sell", "TEXT"),
            "changeInPrice": ("change_in_price", "REAL"),
            "changeInQuantity": ("change_in_quantity", "REAL"),
            "clearingFirmID": ("clearing_firm_id", "TEXT"),
            "closePrice": ("close_price", "REAL"),
            "commodityType": ("commodity_type", "TEXT"),
            "conid": ("conid", "TEXT"),
            "cost": ("cost", "REAL"),
            "currency": ("currency", "TEXT"),
            "cusip": ("cusip", "TEXT"),
            "dateTime": ("date_time", "TEXT"),
            "deliveryType": ("delivery_type", "TEXT"),
            "description": ("description", "TEXT"),
            "exchOrderId": ("exch_order_id", "TEXT"),
            "exchange": ("exchange", "TEXT"),
            "expiry": ("expiry", "TEXT"),
            "extExecID": ("ext_exec_id", "TEXT"),
            "fifoPnlRealized": ("fifo_pnl_realized", "REAL"),
            "figi": ("figi", "TEXT"),
            "fineness": ("fineness", "REAL"),
            "fxRateToBase": ("fx_rate_to_base", "REAL"),
            "holdingPeriodDateTime": ("holding_period_date_time", "TEXT"),
            "ibCommission": ("ib_commission", "REAL"),
            "ibCommissionCurrency": ("ib_commission_currency", "REAL"),
            "ibExecID": ("ib_exec_id", "TEXT"),
            "ibOrderID": ("ib_order_id", "TEXT"),
            "initialInvestment": ("initial_investment", "TEXT"),
            "isAPIOrder": ("is_api_order", "TEXT"),
            "isin": ("isin", "TEXT"),
            "issuer": ("issuer", "TEXT"),
            "issuerCountryCode": ("issuer_country_code", "TEXT"),
            "levelOfDetail": ("level_of_detail", "TEXT"),
            "listingExchange": ("listing_exchange", "TEXT"),
            "model": ("model", "TEXT"),
            "mtmPnl": ("mtm_pnl", "REAL"),
            "multiplier": ("multiplier", "REAL"),
            "netCash": ("net_cash", "REAL"),
            "notes": ("notes", "TEXT"),
            "openCloseIndicator": ("open_close_indicator", "TEXT"),
            "openDateTime": ("open_date_time", "TEXT"),
            "orderReference": ("order_reference", "TEXT"),
            "orderTime": ("order_time", "TEXT"),
            "orderType": ("order_type", "TEXT"),
            "origOrderID": ("orig_order_id", "TEXT"),
            "origTradeDate": ("orig_trade_date", "TEXT"),
            "origTradeID": ("orig_trade_id", "TEXT"),
            "origTradePrice": ("orig_trade_price", "REAL"),
            "origTransactionID": ("orig_transaction_id", "TEXT"),
            "positionActionID": ("position_action_id", "TEXT"),
            "principalAdjustFactor": ("principal_adjust_factor", "REAL"),
            "proceeds": ("proceeds", "REAL"),
            "putCall": ("put_call", "TEXT"),
            "quantity": ("quantity", "REAL"),
            "relatedTradeID": ("related_trade_id", "TEXT"),
            "relatedTransactionID": ("related_transaction_id", "TEXT"),
            "reportDate": ("report_date", "TEXT"),
            "rtn": ("rtn", "TEXT"),
            "securityID": ("security_id", "TEXT"),
            "securityIDType": ("security_id_type", "TEXT"),
            "serialNumber": ("serial_number", "TEXT"),
            "settleDateTarget": ("settle_date_target", "TEXT"),
            "strike": ("strike", "REAL"),
            "subCategory": ("sub_category", "TEXT"),
            "symbol": ("symbol", "TEXT"),
            "taxes": ("taxes", "REAL"),
            "tradeDate": ("trade_date", "TEXT"),
            "tradeID": ("trade_id", "TEXT"),
            "tradeMoney": ("trade_money", "REAL"),
            "tradePrice": ("trade_price", "REAL"),
            "traderID": ("trader_id", "TEXT"),
            "transactionID": ("transaction_id", "TEXT"),
            "transactionType": ("transaction_type", "TEXT"),
            "underlyingConid": ("underlying_conid", "TEXT"),
            "underlyingListingExchange": ("underlying_listing_exchange", "TEXT"),
            "underlyingSecurityID": ("underlying_security_id", "TEXT"),
            "underlyingSymbol": ("underlying_symbol", "TEXT"),
            "volatilityOrderLink": ("volatility_order_link", "TEXT"),
            "weight": ("weight", "REAL"),
            "whenRealized": ("when_realized", "TEXT"),
            "whenReopened": ("when_reopened", "TEXT"),
        },
    },
    "AccountInformation": {
        "table": "flex_account_information",
        "key": "row_uid",
        "columns": {
            "accountCapabilities": ("account_capabilities", "TEXT"),
            "accountId": ("account_id", "TEXT"),
            "accountRepName": ("account_rep_name", "TEXT"),
            "accountRepPhone": ("account_rep_phone", "TEXT"),
            "accountType": ("account_type", "TEXT"),
            "acctAlias": ("acct_alias", "TEXT"),
            "beneficiaryDesignations": ("beneficiary_designations", "TEXT"),
            "city": ("city", "TEXT"),
            "cityResidentialAddress": ("city_residential_address", "TEXT"),
            "country": ("country", "TEXT"),
            "countryResidentialAddress": ("country_residential_address", "TEXT"),
            "currency": ("currency", "TEXT"),
            "customerType": ("customer_type", "TEXT"),
            "dateClosed": ("date_closed", "TEXT"),
            "dateFunded": ("date_funded", "TEXT"),
            "dateOfBirth": ("date_of_birth", "TEXT"),
            "dateOpened": ("date_opened", "TEXT"),
            "dividendReinvestmentEnabled": ("dividend_reinvestment_enabled", "TEXT"),
            "hasPendingTasks": ("has_pending_tasks", "TEXT"),
            "ibEntity": ("ib_entity", "TEXT"),
            "lastTradedDate": ("last_traded_date", "TEXT"),
            "masterName": ("master_name", "TEXT"),
            "model": ("model", "TEXT"),
            "name": ("name", "TEXT"),
            "postalCode": ("postal_code", "INTEGER"),
            "postalCodeResidentialAddress": ("postal_code_residential_address", "INTEGER"),
            "primaryEmail": ("primary_email", "TEXT"),
            "recurringTransactions": ("recurring_transactions", "TEXT"),
            "state": ("state", "TEXT"),
            "stateResidentialAddress": ("state_residential_address", "TEXT"),
            "street": ("street", "TEXT"),
            "street2": ("street2", "TEXT"),
            "street2ResidentialAddress": ("street2_residential_address", "TEXT"),
            "streetResidentialAddress": ("street_residential_address", "TEXT"),
            "syepEnrollmentStatus": ("syep_enrollment_status", "TEXT"),
            "taxLotMatchingMethod": ("tax_lot_matching_method", "TEXT"),
            "tradingPermissions": ("trading_permissions", "TEXT"),
        },
    },
    "ChangeInNAV": {
        "table": "flex_change_in_nav",
        "key": "row_uid",
        "columns": {
            "accountId": ("account_id", "TEXT"),
            "acctAlias": ("acct_alias", "TEXT"),
            "advisorFees": ("advisor_fees", "REAL"),
            "assetTransfers": ("asset_transfers", "INTEGER"),
            "billPay": ("bill_pay", "INTEGER"),
            "billableSalesTax": ("billable_sales_tax", "REAL"),
            "brokerFees": ("broker_fees", "REAL"),
            "carbonCredits": ("carbon_credits", "REAL"),
            "changeInBrokerFeeAccruals": ("change_in_broker_fee_accruals", "REAL"),
            "changeInCGTWithholdingAccruals": ("change_in_cgt_withholding_accruals", "INTEGER"),
            "changeInDividendAccruals": ("change_in_dividend_accruals", "REAL"),
            "changeInIncentiveCouponAccruals": ("change_in_incentive_coupon_accruals", "INTEGER"),
            "changeInInterestAccruals": ("change_in_interest_accruals", "REAL"),
            "changeInLiteSurchargeAccruals": ("change_in_lite_surcharge_accruals", "INTEGER"),
            "changeInUnrealized": ("change_in_unrealized", "INTEGER"),
            "clientFees": ("client_fees", "REAL"),
            "commissionCreditsRedemption": ("commission_credits_redemption", "REAL"),
            "commissionReceivables": ("commission_receivables", "REAL"),
            "commissions": ("commissions", "REAL"),
            "commissionsAtPaxos": ("commissions_at_paxos", "REAL"),
            "corporateActionProceeds": ("corporate_action_proceeds", "REAL"),
            "costAdjustments": ("cost_adjustments", "REAL"),
            "currency": ("currency", "TEXT"),
            "debitCardActivity": ("debit_card_activity", "REAL"),
            "depositsWithdrawals": ("deposits_withdrawals", "REAL"),
            "dividends": ("dividends", "REAL"),
            "donations": ("donations", "INTEGER"),
            "endingValue": ("ending_value", "REAL"),
            "excessFundSweep": ("excess_fund_sweep", "INTEGER"),
            "feesReceivables": ("fees_receivables", "REAL"),
            "forexCommissions": ("forex_commissions", "REAL"),
            "fromDate": ("from_date", "TEXT"),
            "fxTranslation": ("fx_translation", "REAL"),
            "grantActivity": ("grant_activity", "INTEGER"),
            "interest": ("interest", "REAL"),
            "internalCashTransfers": ("internal_cash_transfers", "REAL"),
            "linkingAdjustments": ("linking_adjustments", "REAL"),
            "model": ("model", "TEXT"),
            "mtm": ("mtm", "REAL"),
            "mtmAtPaxos": ("mtm_at_paxos", "INTEGER"),
            "netFxTrading": ("net_fx_trading", "INTEGER"),
            "other": ("other", "INTEGER"),
            "otherFees": ("other_fees", "REAL"),
            "otherIncome": ("other_income", "INTEGER"),
            "paxosTransfers": ("paxos_transfers", "INTEGER"),
            "realized": ("realized", "INTEGER"),
            "referralFee": ("referral_fee", "REAL"),
            "salesTax": ("sales_tax", "REAL"),
            "softDollars": ("soft_dollars", "INTEGER"),
            "startingValue": ("starting_value", "REAL"),
            "taxReceivables": ("tax_receivables", "REAL"),
            "toDate": ("to_date", "TEXT"),
            "transactionTax": ("transaction_tax", "REAL"),
            "transferredPnlAdjustments": ("transferred_pnl_adjustments", "REAL"),
            "twr": ("twr", "REAL"),
            "withholding871m": ("withholding871m", "INTEGER"),
            "withholdingTax": ("withholding_tax", "REAL"),
            "withholdingTaxCollected": ("withholding_tax_collected", "REAL"),
        },
    },
}

#: Every attribute name seen in the audited archive, per element.
KNOWN_ATTRIBUTES: dict[str, frozenset[str]] = {
    "ConversionRate": frozenset({"fromCurrency", "rate", "reportDate", "toCurrency"}),
    "StatementOfFundsLine": frozenset(
        {
            "accountId",
            "acctAlias",
            "actionID",
            "activityCode",
            "activityDescription",
            "amount",
            "assetCategory",
            "balance",
            "buySell",
            "commodityType",
            "conid",
            "credit",
            "currency",
            "cusip",
            "date",
            "debit",
            "deliveryType",
            "description",
            "expiry",
            "figi",
            "fineness",
            "fxRateToBase",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "multiplier",
            "orderID",
            "origTransactionID",
            "principalAdjustFactor",
            "putCall",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDate",
            "strike",
            "subCategory",
            "symbol",
            "tradeCode",
            "tradeCommission",
            "tradeGross",
            "tradeID",
            "tradePrice",
            "tradeQuantity",
            "tradeTax",
            "transactionID",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "weight",
        }
    ),
    "Trade": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "UnbundledCommissionDetail": frozenset(
        {
            "accountId",
            "acctAlias",
            "assetCategory",
            "brokerClearingCharge",
            "brokerExecutionCharge",
            "buySell",
            "commodityType",
            "conid",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchange",
            "expiry",
            "figi",
            "fineness",
            "fxRateToBase",
            "isin",
            "issuer",
            "issuerCountryCode",
            "listingExchange",
            "model",
            "multiplier",
            "orderReference",
            "other",
            "price",
            "principalAdjustFactor",
            "putCall",
            "quantity",
            "regFINRATradingActivityFee",
            "regOther",
            "regSection31TransactionFee",
            "securityID",
            "securityIDType",
            "serialNumber",
            "strike",
            "subCategory",
            "symbol",
            "thirdPartyClearingCharge",
            "thirdPartyExecutionCharge",
            "thirdPartyRegulatoryCharge",
            "totalCommission",
            "tradeID",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "weight",
        }
    ),
    "Order": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "Lot": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "CashTransaction": frozenset(
        {
            "accountId",
            "acctAlias",
            "actionID",
            "amount",
            "assetCategory",
            "availableForTradingDate",
            "clientReference",
            "code",
            "commodityType",
            "conid",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "dividendType",
            "exDate",
            "expiry",
            "figi",
            "fineness",
            "fxRateToBase",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "multiplier",
            "principalAdjustFactor",
            "putCall",
            "reportDate",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDate",
            "strike",
            "subCategory",
            "symbol",
            "tradeID",
            "transactionID",
            "type",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "weight",
        }
    ),
    "WashSale": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "SymbolSummary": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "SecurityInfo": frozenset(
        {
            "assetCategory",
            "code",
            "commodityType",
            "conid",
            "currency",
            "cusip",
            "deliveryType",
            "description",
            "expiry",
            "figi",
            "fineness",
            "isin",
            "issueDate",
            "issuer",
            "issuerCountryCode",
            "listingExchange",
            "maturity",
            "multiplier",
            "principalAdjustFactor",
            "putCall",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settlementPolicyMethod",
            "strike",
            "subCategory",
            "symbol",
            "underlyingCategory",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "weight",
        }
    ),
    "OpenPosition": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "code",
            "commodityType",
            "conid",
            "costBasisMoney",
            "costBasisPrice",
            "currency",
            "cusip",
            "deliveryType",
            "description",
            "expiry",
            "fifoPnlUnrealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "markPrice",
            "model",
            "multiplier",
            "openDateTime",
            "openPrice",
            "originatingOrderID",
            "originatingTransactionID",
            "percentOfNAV",
            "position",
            "positionValue",
            "principalAdjustFactor",
            "putCall",
            "reportDate",
            "securityID",
            "securityIDType",
            "serialNumber",
            "side",
            "strike",
            "subCategory",
            "symbol",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "vestingDate",
            "weight",
        }
    ),
    "AssetSummary": frozenset(
        {
            "accountId",
            "accruedInt",
            "acctAlias",
            "assetCategory",
            "brokerageOrderID",
            "buySell",
            "changeInPrice",
            "changeInQuantity",
            "clearingFirmID",
            "closePrice",
            "commodityType",
            "conid",
            "cost",
            "currency",
            "cusip",
            "dateTime",
            "deliveryType",
            "description",
            "exchOrderId",
            "exchange",
            "expiry",
            "extExecID",
            "fifoPnlRealized",
            "figi",
            "fineness",
            "fxRateToBase",
            "holdingPeriodDateTime",
            "ibCommission",
            "ibCommissionCurrency",
            "ibExecID",
            "ibOrderID",
            "initialInvestment",
            "isAPIOrder",
            "isin",
            "issuer",
            "issuerCountryCode",
            "levelOfDetail",
            "listingExchange",
            "model",
            "mtmPnl",
            "multiplier",
            "netCash",
            "notes",
            "openCloseIndicator",
            "openDateTime",
            "orderReference",
            "orderTime",
            "orderType",
            "origOrderID",
            "origTradeDate",
            "origTradeID",
            "origTradePrice",
            "origTransactionID",
            "positionActionID",
            "principalAdjustFactor",
            "proceeds",
            "putCall",
            "quantity",
            "relatedTradeID",
            "relatedTransactionID",
            "reportDate",
            "rtn",
            "securityID",
            "securityIDType",
            "serialNumber",
            "settleDateTarget",
            "strike",
            "subCategory",
            "symbol",
            "taxes",
            "tradeDate",
            "tradeID",
            "tradeMoney",
            "tradePrice",
            "traderID",
            "transactionID",
            "transactionType",
            "underlyingConid",
            "underlyingListingExchange",
            "underlyingSecurityID",
            "underlyingSymbol",
            "volatilityOrderLink",
            "weight",
            "whenRealized",
            "whenReopened",
        }
    ),
    "AccountInformation": frozenset(
        {
            "accountCapabilities",
            "accountId",
            "accountRepName",
            "accountRepPhone",
            "accountType",
            "acctAlias",
            "beneficiaryDesignations",
            "city",
            "cityResidentialAddress",
            "country",
            "countryResidentialAddress",
            "currency",
            "customerType",
            "dateClosed",
            "dateFunded",
            "dateOfBirth",
            "dateOpened",
            "dividendReinvestmentEnabled",
            "hasPendingTasks",
            "ibEntity",
            "lastTradedDate",
            "masterName",
            "model",
            "name",
            "postalCode",
            "postalCodeResidentialAddress",
            "primaryEmail",
            "recurringTransactions",
            "state",
            "stateResidentialAddress",
            "street",
            "street2",
            "street2ResidentialAddress",
            "streetResidentialAddress",
            "syepEnrollmentStatus",
            "taxLotMatchingMethod",
            "tradingPermissions",
        }
    ),
    "ChangeInNAV": frozenset(
        {
            "accountId",
            "acctAlias",
            "advisorFees",
            "assetTransfers",
            "billPay",
            "billableSalesTax",
            "brokerFees",
            "carbonCredits",
            "changeInBrokerFeeAccruals",
            "changeInCGTWithholdingAccruals",
            "changeInDividendAccruals",
            "changeInIncentiveCouponAccruals",
            "changeInInterestAccruals",
            "changeInLiteSurchargeAccruals",
            "changeInUnrealized",
            "clientFees",
            "commissionCreditsRedemption",
            "commissionReceivables",
            "commissions",
            "commissionsAtPaxos",
            "corporateActionProceeds",
            "costAdjustments",
            "currency",
            "debitCardActivity",
            "depositsWithdrawals",
            "dividends",
            "donations",
            "endingValue",
            "excessFundSweep",
            "feesReceivables",
            "forexCommissions",
            "fromDate",
            "fxTranslation",
            "grantActivity",
            "interest",
            "internalCashTransfers",
            "linkingAdjustments",
            "model",
            "mtm",
            "mtmAtPaxos",
            "netFxTrading",
            "other",
            "otherFees",
            "otherIncome",
            "paxosTransfers",
            "realized",
            "referralFee",
            "salesTax",
            "softDollars",
            "startingValue",
            "taxReceivables",
            "toDate",
            "transactionTax",
            "transferredPnlAdjustments",
            "twr",
            "withholding871m",
            "withholdingTax",
            "withholdingTaxCollected",
        }
    ),
}
