"""PineScript v5 generator — strategy and indicator scripts from backtest results and signals."""
from __future__ import annotations

import re
from typing import Any

import pandas as pd


def _sanitize(value: str, max_len: int = 128) -> str:
    """Strip characters that could escape a PineScript string literal or inject code.

    PineScript string literals are delimited by double-quotes.  A raw ``"``
    inside *name* / *symbol* would close the literal early; a newline would
    break the generated line.  We replace both with a space and truncate to a
    safe length so callers cannot inject arbitrary PineScript.
    """
    cleaned = re.sub(r'["\n\r]', " ", str(value))
    return cleaned[:max_len]

_INDICATOR_SNIPPETS: dict[str, str] = {
    "rsi": """\
// RSI
rsiLength = input.int({rsi_period}, "RSI Length")
rsiValue = ta.rsi(close, rsiLength)
plot(rsiValue, "RSI", color.new(color.purple, 0))
hline(70, "Overbought", color.red)
hline(30, "Oversold", color.green)
""",
    "macd": """\
// MACD
[macdLine, signalLine, hist] = ta.macd(close, {macd_fast}, {macd_slow}, {macd_signal})
plot(macdLine, "MACD", color.blue)
plot(signalLine, "Signal", color.orange)
plot(hist, "Histogram", color.gray, style=plot.style_histogram)
""",
    "bollinger_bands": """\
// Bollinger Bands
bbLength = input.int({bb_period}, "BB Length")
bbMult = input.float({bb_std}, "BB Std Dev")
[bbUpper, bbMid, bbLower] = ta.bb(close, bbLength, bbMult)
plot(bbUpper, "BB Upper", color.red)
plot(bbMid, "BB Mid", color.gray)
plot(bbLower, "BB Lower", color.green)
""",
    "ema": """\
// EMA
emaLength = input.int({ema_period}, "EMA Length")
emaValue = ta.ema(close, emaLength)
plot(emaValue, "EMA", color.orange)
""",
    "sma": """\
// SMA
smaLength = input.int({sma_period}, "SMA Length")
smaValue = ta.sma(close, smaLength)
plot(smaValue, "SMA", color.blue)
""",
    "atr": """\
// ATR
atrLength = input.int({atr_period}, "ATR Length")
atrValue = ta.atr(atrLength)
plot(atrValue, "ATR", color.purple)
""",
}

_PARAM_DEFAULTS = {
    "rsi_period": 14,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "bb_period": 20,
    "bb_std": 2.0,
    "ema_period": 20,
    "sma_period": 20,
    "atr_period": 14,
}


def strategy_from_signals(
    name: str,
    signals: pd.Series,
    symbol: str,
    timeframe: str,
) -> str:
    """Generate a PineScript v5 strategy from a signal series (1=long, 0=flat, -1=short)."""
    safe_name = _sanitize(name)
    safe_symbol = _sanitize(symbol)
    safe_timeframe = _sanitize(timeframe)
    long_entries = int((signals.diff() == 1).sum() + (signals.iloc[0] == 1))
    short_entries = int((signals.diff() == -1).sum() + (signals.iloc[0] == -1))

    return f"""//@version=5
// Generated by ibkr_core_mcp — {safe_name}
// Symbol: {safe_symbol} | Timeframe: {safe_timeframe}
// Signal stats: {long_entries} long entries, {short_entries} short entries
strategy("{safe_name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// ── Signal logic (replace with your conditions) ─────────────────────────────
// This script uses a simplified representation of the original signal series.
// Reconstruct your entry conditions below based on your indicator logic.

longCondition = ta.crossover(ta.ema(close, 12), ta.ema(close, 26))
shortCondition = ta.crossunder(ta.ema(close, 12), ta.ema(close, 26))
exitCondition = false

if longCondition
    strategy.entry("Long", strategy.long)

if shortCondition
    strategy.entry("Short", strategy.short)

if exitCondition
    strategy.close_all()

// ── Visuals ──────────────────────────────────────────────────────────────────
plot(ta.ema(close, 12), "EMA 12", color.green)
plot(ta.ema(close, 26), "EMA 26", color.red)
"""


def indicator_script(
    name: str,
    indicators: list[str],
    params: dict[str, Any],
) -> str:
    """Generate a PineScript v5 indicator study with the requested indicators."""
    safe_name = _sanitize(name)
    merged = {**_PARAM_DEFAULTS, **params}
    snippets = []
    for ind in indicators:
        safe_ind = _sanitize(ind)
        template = _INDICATOR_SNIPPETS.get(ind, f"// Indicator '{safe_ind}' — not yet supported\n")
        try:
            snippets.append(template.format(**merged))
        except KeyError:
            snippets.append(template)

    ind_list = ", ".join(_sanitize(i) for i in indicators)
    return f"""//@version=5
// Generated by ibkr_core_mcp — {safe_name}
// Indicators: {ind_list}
indicator("{safe_name}", overlay={_needs_overlay(indicators)})

{chr(10).join(snippets)}"""


def strategy_from_backtest(
    backtest_result: object,
    df: pd.DataFrame,
) -> str:
    """Generate a PineScript v5 strategy from a BacktestResult + OHLCV DataFrame."""
    name = _sanitize(getattr(backtest_result, "strategy_name", "Exported Strategy"))
    symbol = _sanitize(getattr(backtest_result, "symbol", ""))
    total_return = getattr(backtest_result, "total_return", 0.0)
    sharpe = getattr(backtest_result, "sharpe", 0.0)
    max_dd = getattr(backtest_result, "max_drawdown", 0.0)
    num_trades = getattr(backtest_result, "num_trades", 0)
    win_rate = getattr(backtest_result, "win_rate", 0.0)

    timeframe = _infer_timeframe(df)

    return f"""//@version=5
// Generated by ibkr_core_mcp — {name}
// Symbol: {symbol} | Timeframe: {timeframe}
//
// Backtest Summary:
//   Total Return : {total_return:.1%}
//   Sharpe Ratio : {sharpe:.2f}
//   Max Drawdown : {max_dd:.1%}
//   Num Trades   : {num_trades}
//   Win Rate     : {win_rate:.1%}
//
// ⚠ This script is a starting point. Replicate your entry/exit logic below.
strategy("{name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// ── Inputs ───────────────────────────────────────────────────────────────────
rsiLength  = input.int(14, "RSI Length", minval=2, maxval=50)
rsiOversold  = input.int(30, "RSI Oversold", minval=10, maxval=50)
rsiOverbought = input.int(70, "RSI Overbought", minval=50, maxval=90)

// ── Indicators ───────────────────────────────────────────────────────────────
rsiValue = ta.rsi(close, rsiLength)
[macdLine, signalLine, _hist] = ta.macd(close, 12, 26, 9)

// ── Entry / Exit ─────────────────────────────────────────────────────────────
longEntry  = ta.crossover(rsiValue, rsiOversold)
longExit   = ta.crossunder(rsiValue, rsiOverbought)
shortEntry = ta.crossunder(rsiValue, rsiOverbought)
shortExit  = ta.crossover(rsiValue, rsiOversold)

if longEntry
    strategy.entry("Long", strategy.long)
if longExit
    strategy.close("Long")
if shortEntry
    strategy.entry("Short", strategy.short)
if shortExit
    strategy.close("Short")

// ── Visuals ───────────────────────────────────────────────────────────────────
plot(rsiValue, "RSI", color.purple)
hline(rsiOversold, "Oversold", color.green)
hline(rsiOverbought, "Overbought", color.red)
"""


def _needs_overlay(indicators: list[str]) -> str:
    overlay_indicators = {"sma", "ema", "bollinger_bands", "keltner_channels", "vwap"}
    return "true" if any(i in overlay_indicators for i in indicators) else "false"


def _infer_timeframe(df: pd.DataFrame) -> str:
    if len(df) < 2:
        return "1D"
    try:
        delta = df.index[1] - df.index[0]
        minutes = int(delta.total_seconds() / 60)
    except (AttributeError, TypeError):
        return "1D"
    if minutes <= 1:
        return "1"
    if minutes <= 5:
        return "5"
    if minutes <= 60:
        return f"{minutes}"
    if minutes <= 1440:
        return "1D"
    return "1W"
